package io.github.uprxiao.audit.finding;

public enum IssueCategory {
    CORRECTNESS,
    WEB_SECURITY,
    CONCURRENCY,
    RESOURCE_PERFORMANCE,
    MAINTAINABILITY,
    CODE_STYLE,
    DUPLICATION,
    SECRET_EXPOSURE,
    DEPENDENCY_VULNERABILITY,
    BUILD_GOVERNANCE,
    CONFIG_IAC_SECURITY,
    LICENSE_SUPPLY_CHAIN
}
