package io.github.uprxiao.audit.api;

public enum ApiErrorCode {
    INVALID_REQUEST,
    INVALID_MAVEN_ARGUMENT,
    UNSUPPORTED_SOURCE,
    UNSAFE_ARCHIVE_ENTRY,
    ARCHIVE_LIMIT_EXCEEDED,
    NO_MAVEN_ROOT,
    MULTIPLE_MAVEN_ROOTS,
    UNSUPPORTED_JAVA_VERSION,
    PROFILE_UNAVAILABLE,
    TOOL_UNAVAILABLE,
    SCAN_NOT_FOUND,
    INVALID_SCAN_STATE,
    REPORT_NOT_READY,
    REPORT_EXPIRED,
    QUEUE_FULL,
    DISK_SPACE_LOW,
    CORRUPTED_STATE,
    INTERNAL_ERROR
}
